# pose displacement
float64[6] r # [rx, ry, rz, roll, pitch, yaw]
# phase shift
float64[6] phi  # [phi_x, phi_y, phi_z, phi_roll, phi_pitch, phi_yaw]
# motion frequency and duration
float64 w
float64 dance_time_millis
---
string result_message
---
