services:
  raspberry-penta-jazzy-ros2:
    build:
      context: ../
      args:
        COLCON_WORKSPACE: /root/ros_ws
    volumes:
      - ../../../:/root/ros_ws
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./entrypoint.sh:/root/ros_ws/src/polypod/.devcontainer/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=95
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    privileged: true
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/i2c-1:/dev/i2c-1
      - /dev/dri:/dev/dri
    tty: true
    command: [ "/bin/bash", "-c", "/root/ros_ws/src/polypod/.devcontainer/entrypoint.sh" ]

