services:
  penta-jazzy-ros2:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      args:
        COLCON_WORKSPACE: /root/ros_ws
    volumes:
      - ../:/root/ros_ws/src
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./entrypoint.sh:/root/ros_ws/src/.devcontainer/entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=91
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    privileged: true
    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/i2c-0:/dev/i2c-0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/dri:/dev/dri
    tty: true
    command: [ "/bin/bash", "-c", "/root/ros_ws/src/.devcontainer/entrypoint.sh" ]

  penta-jazzy-ros2-test:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      args:
        COLCON_WORKSPACE: /root/ros_ws
    volumes:
      - ../:/root/ros_ws/src
    environment:
      - ROS_DOMAIN_ID=91
    network_mode: "host"
    command: [ "/bin/bash", "-c", "source /opt/ros/jazzy/setup.bash && cd /root/ros_ws && colcon test" ]
