/**:
  ros__parameters:
    interval_millis: 20
    kp: 2.0
    mounting: # in degrees
      roll: 0.0
      pitch: 0.0
      yaw: -90.0
    tilt_limits: # tan
      tan_x: 0.35
      tan_y: 0.35
      tan_z: 0.35
    joy:
      enable_button_index: 3
